/**
 * Convert snarkjs Groth16 artifacts (BLS12-381) into the byte encoding the
 * Soroban host expects (CAP-0059):
 *
 *   Fp  : 48-byte big-endian
 *   G1  : be(X) || be(Y)                                   (96 bytes)
 *   G2  : be(X_c1) || be(X_c0) || be(Y_c1) || be(Y_c0)     (192 bytes)
 *   Fr  : 32-byte big-endian
 *
 * The Groth16 check e(A,B) = e(alpha,beta) * e(vk_x,gamma) * e(C,delta) is
 * rearranged to a single product-of-pairings == 1 by negating alpha (G1),
 * gamma and delta (G2) here, off-chain, so the contract never needs field
 * negation:
 *
 *   e(A,B) * e(-alpha,beta) * e(vk_x,-gamma) * e(C,-delta) == 1
 *
 * Outputs build/soroban_vk.json and build/soroban_proof.json, and (with
 * --rust <path>) a Rust test-vector file for the verifier contract.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

// BLS12-381 base field modulus.
const P = BigInt(
  "0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f624" +
    "1eabfffeb153ffffb9feffffffffaaab"
);

const fp = (dec) => BigInt(dec).toString(16).padStart(96, "0");
const fr = (dec) => BigInt(dec).toString(16).padStart(64, "0");

function g1(point) {
  const [x, y, z] = point;
  if (BigInt(z) !== 1n) throw new Error("expected affine G1 point (z == 1)");
  return fp(x) + fp(y);
}

function g1Neg(point) {
  const [x, y, z] = point;
  if (BigInt(z) !== 1n) throw new Error("expected affine G1 point (z == 1)");
  return fp(x) + fp((P - (BigInt(y) % P)) % P);
}

function g2(point) {
  const [[xc0, xc1], [yc0, yc1], [zc0, zc1]] = point;
  if (BigInt(zc0) !== 1n || BigInt(zc1) !== 0n) throw new Error("expected affine G2 point");
  return fp(xc1) + fp(xc0) + fp(yc1) + fp(yc0);
}

function g2Neg(point) {
  const [[xc0, xc1], [yc0, yc1], [zc0, zc1]] = point;
  if (BigInt(zc0) !== 1n || BigInt(zc1) !== 0n) throw new Error("expected affine G2 point");
  const negY = (c) => (P - (BigInt(c) % P)) % P;
  return fp(xc1) + fp(xc0) + fp(negY(yc1).toString()) + fp(negY(yc0).toString());
}

export function exportVk(vk) {
  if (vk.curve !== "bls12381") throw new Error(`expected bls12381 curve, got ${vk.curve}`);
  return {
    alpha_neg: g1Neg(vk.vk_alpha_1),
    beta: g2(vk.vk_beta_2),
    gamma_neg: g2Neg(vk.vk_gamma_2),
    delta_neg: g2Neg(vk.vk_delta_2),
    ic: vk.IC.map(g1),
  };
}

export function exportProof(proof, publicSignals) {
  if (proof.curve !== "bls12381") throw new Error(`expected bls12381 curve, got ${proof.curve}`);
  return {
    a: g1(proof.pi_a),
    b: g2(proof.pi_b),
    c: g1(proof.pi_c),
    public_inputs: publicSignals.map(fr),
  };
}

function toRust(vk, proof) {
  const icArray = vk.ic.map((h) => `    "${h}",`).join("\n");
  const inputsArray = proof.public_inputs.map((h) => `    "${h}",`).join("\n");
  return `//! Generated by zkml/scripts/export_soroban.js — do not edit by hand.
//! Real Groth16 (BLS12-381) verification key and proof produced by snarkjs
//! for zkml/circuits/strategy.circom with zkml/inputs/sample_trade.json.

pub const VK_ALPHA_NEG: &str = "${vk.alpha_neg}";
pub const VK_BETA: &str = "${vk.beta}";
pub const VK_GAMMA_NEG: &str = "${vk.gamma_neg}";
pub const VK_DELTA_NEG: &str = "${vk.delta_neg}";
pub const VK_IC: &[&str] = &[
${icArray}
];

pub const PROOF_A: &str = "${proof.a}";
pub const PROOF_B: &str = "${proof.b}";
pub const PROOF_C: &str = "${proof.c}";
pub const PUBLIC_INPUTS: &[&str] = &[
${inputsArray}
];
`;
}

const isDirectRun = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  const vk = exportVk(JSON.parse(readFileSync(resolve(root, "build/verification_key.json"), "utf8")));
  const proof = exportProof(
    JSON.parse(readFileSync(resolve(root, "build/strategy.proof"), "utf8")),
    JSON.parse(readFileSync(resolve(root, "build/public.json"), "utf8"))
  );

  writeFileSync(resolve(root, "build/soroban_vk.json"), JSON.stringify(vk, null, 2));
  writeFileSync(resolve(root, "build/soroban_proof.json"), JSON.stringify(proof, null, 2));

  const rustFlag = process.argv.indexOf("--rust");
  if (rustFlag !== -1 && process.argv[rustFlag + 1]) {
    writeFileSync(resolve(process.argv[rustFlag + 1]), toRust(vk, proof));
  }
  console.log(
    JSON.stringify({ ok: true, ic_points: vk.ic.length, public_inputs: proof.public_inputs.length })
  );
}
